name: Codex Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  codex-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Debug environment for troubleshooting
      - name: Debug environment
        run: |
          which codex || echo "codex not found"
          python --version || true
          pip --version || true

      # Install Codex CLI
      - name: Install Codex CLI
        run: |
          pip install --upgrade pip
          pip install codex-cli

      # Authenticate Codex (only if token exists)
      - name: Auth to Codex
        if: ${{ secrets.CODEX_TOKEN != '' }}
        run: codex auth --token ${{ secrets.CODEX_TOKEN }}

      # Run Codex Sync
      - name: Codex Sync
        run: codex sync --project audiojones.com
