name: Codex Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codex-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Codex CLI
        run: pip install codex-cli

      - name: Authenticate Codex
        run: codex auth --token ${{ secrets.CODEX_TOKEN }}

      - name: Run Codex Sync
        run: codex sync --project audiojones.com
